name: openapi_client_delegates
description: Openapi Client Delegates for printing and mocking openapi generated responses
version: 0.1.0
homepage: https://github.com/ahmetcj4/openapi_client_delegates

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  openapi_dart_common: ^4.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter